services:
  web-ui:
    container_name: ria.e-its.ui
    build:
      context: ./eits.web-ui
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    container_name: ria.e-its.api
    build:
      context: ./eits.backoffice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"