services:
  web-ui:
    container_name: ria.e-its.ui
    build:
      context: ./webapp
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    container_name: ria.e-its.api
    build:
      context: ./core/client
    ports:
      - "8080:8080"